
package com.crossfit.youtube;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.0.0-milestone2
 * 2019-05-22T16:22:30.323+01:00
 * Generated source version: 3.0.0-milestone2
 * 
 */
 
public class Youtube_YoutubeSOAP_Server{

    protected Youtube_YoutubeSOAP_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new youtubeSOAPImpl();
        String address = "http://localhost:8080/ss/youtubeSOAP";
        Endpoint.publish(address, implementor);
    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new Youtube_YoutubeSOAP_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5 * 60 * 1000); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
